"""Local Gemini-driven evolutionary controller that speaks the AlphaEvolve contract.

This is NOT AlphaEvolve. It exists so real, budgeted, evidence-producing runs can happen today while
the Gemini Enterprise app with AlphaEvolve is not provisioned. It uses the same evaluator contract,
EVOLVE-BLOCK packaging, sandbox, baseline lock, budget ledger, holdout rescoring and evidence schema as
the production adapter (alphaevolve_adapter.py), so switching is one flag (``--backend alphaevolve``).
Evidence carries ``source: "local-gemini-controller"``; ``evolved`` never flips for these runs.

Search: islands (default 3) with a MAP-Elites-lite archive per island over a 2-D behaviour descriptor
supplied by the problem; parent = rank-weighted exploit (60%) or random elite (40%); inspirations = the
island's top programs + an elite from another island + the global best; ring migration every 10
programs. Mutations are AlphaEvolve SEARCH/REPLACE diffs inside the EVOLVE-BLOCK, generated by a
weighted model mix (balanced 0.7 / reasoning 0.3).
"""
from __future__ import annotations

import hashlib
import math
import random
import threading
import time
from concurrent.futures import FIRST_COMPLETED, Future, ThreadPoolExecutor, wait
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from .. import model_policy
from ..config import SOURCE_DRY_RUN, SOURCE_LOCAL
from ..problems.base import ProblemSpec, load_manifest
from .baseline import verify_baseline
from .budget import BudgetPolicy, Ledger, PlateauTracker, policy_dict
from .contract import KIND_DIFF, EvalOutcome
from .diff import DiffError, apply_reply, diff_stats, unified
from .evaluate import evaluate_candidate
from .evidence import SCHEMA, EvidenceWriter
from .package import END, START, assemble

SYSTEM_PROMPT = """You are an expert quantitative developer and energy-market economist working on an \
evolutionary code search (AlphaEvolve-style). You improve ONE Python policy block for a Japanese electricity \
retailer. You must respect the stated regulatory and fairness invariants: a candidate that violates any of them \
is scored invalid, and raising the score by breaking an invariant is not an improvement.

Output format (strict):
1. A short rationale (2-5 sentences) naming the economic mechanism you are exploiting.
2. One or more diff blocks that edit ONLY the code inside the EVOLVE-BLOCK, exactly in this format:
<<<<<<< SEARCH
<lines copied exactly from the current EVOLVE-BLOCK>
=======
<replacement lines>
>>>>>>> REPLACE
Rules: SEARCH text must match the current block exactly (including indentation). Do not include the \
EVOLVE-BLOCK marker lines. Keep required function names and signatures. Only these imports are allowed: math, \
numpy, statistics, itertools, functools, collections, heapq, bisect, dataclasses, typing, operator, copy. No I/O, \
no randomness, no global mutable state, no dunder access, no eval/exec/getattr. Code must be deterministic and fast."""


@dataclass
class Candidate:
    idx: int
    id: str
    parent_id: str | None
    island: int
    block: str
    model: str = "seed"
    outcome: EvalOutcome | None = None
    rationale: str = ""
    gen: dict = field(default_factory=dict)
    diff_report: dict = field(default_factory=dict)
    created: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    descriptor: tuple[int, int] | None = None
    inspirations: list[str] = field(default_factory=list)
    reply: str = ""

    @property
    def score(self) -> float | None:
        return self.outcome.score if self.outcome else None

    @property
    def block_sha(self) -> str:
        return hashlib.sha256(self.block.encode()).hexdigest()[:16]


def _pid(block: str, idx: int) -> str:
    return f"p{idx:03d}-{hashlib.sha256(block.encode()).hexdigest()[:8]}"


class LocalController:
    def __init__(self, spec: ProblemSpec, mutator, *, max_programs: int | None = None, islands: int = 3,
                 policy: BudgetPolicy | None = None, ledger: Ledger | None = None, runs_dir=None,
                 rng_seed: int = 7, top_k_holdout: int = 5, dry_run: bool = False, log=print):
        self.spec = spec
        self.mutator = mutator
        self.policy = policy or BudgetPolicy.from_env()
        self.max_programs = min(max_programs or self.policy.max_programs_per_run, self.policy.max_programs_per_run)
        self.n_islands = islands
        self.ledger = ledger or Ledger()
        self.runs_dir = runs_dir
        self.rng = random.Random(rng_seed)
        self.top_k = top_k_holdout
        self.dry_run = dry_run
        self.source = SOURCE_DRY_RUN if dry_run else SOURCE_LOCAL
        self.log = log
        self.seed_prog = spec.seed_program
        self.cands: list[Candidate] = []
        self.island_members: dict[int, list[int]] = {i: [] for i in range(islands)}
        self.archive: dict[tuple[int, tuple[int, int]], int] = {}
        self.lock = threading.Lock()
        self.tokens = {"prompt": 0, "output": 0, "thinking": 0, "calls": 0, "errors": 0, "cost_usd": 0.0,
                       "by_model": {}}
        self.stopped_reason = None

    # -- selection ---------------------------------------------------------------------------------
    def _valid(self, idxs):
        return [i for i in idxs if self.cands[i].score is not None]

    def _select_parent(self, island: int) -> Candidate:
        members = self._valid(self.island_members[island]) or [0]
        if self.rng.random() < 0.6:
            ranked = sorted(members, key=lambda i: self.cands[i].score, reverse=True)
            w = [math.exp(-r / 2.0) for r in range(len(ranked))]
            return self.cands[self.rng.choices(ranked, weights=w)[0]]
        elites = [v for (isl, _), v in self.archive.items() if isl == island] or members
        return self.cands[self.rng.choice(elites)]

    def _inspirations(self, island: int, parent: Candidate) -> list[Candidate]:
        seen = {parent.block_sha}
        out: list[Candidate] = []
        ranked = sorted(self._valid(self.island_members[island]), key=lambda i: self.cands[i].score, reverse=True)
        for i in ranked:
            if self.cands[i].block_sha not in seen:
                out.append(self.cands[i])
                seen.add(self.cands[i].block_sha)
            if len(out) >= 2:
                break
        others = [v for (isl, _), v in self.archive.items() if isl != island]
        if others:
            c = self.cands[self.rng.choice(others)]
            if c.block_sha not in seen:
                out.append(c)
                seen.add(c.block_sha)
        gbest = self.best()
        if gbest and gbest.block_sha not in seen:
            out.append(gbest)
        return out[:3]

    def best(self) -> Candidate | None:
        valid = [c for c in self.cands if c.score is not None]
        return max(valid, key=lambda c: c.score) if valid else None

    # -- prompt ------------------------------------------------------------------------------------
    def _recent_invalid(self, n: int = 6) -> list[str]:
        out = []
        for c in reversed(self.cands):
            if c.outcome and not c.outcome.valid and c.outcome.insights:
                l, t = c.outcome.insights[0]
                out.append(f"[{c.outcome.kind}] {l}: {t[:260]}")
            if len(out) >= n:
                break
        return out

    def build_prompt(self, parent: Candidate, insp: list[Candidate]) -> str:
        def fmt_ins(c: Candidate, k: int = 8) -> str:
            if not c.outcome:
                return "(not evaluated)"
            return "\n".join(f"- {l}: {t[:400]}" for l, t in c.outcome.insights[:k])

        parts = [f"# Problem: {self.spec.title}\n\n{self.spec.description}\n",
                 "# Fixed scaffolding (read-only; you may call its helpers)\n```python\n"
                 + self.seed_prog.prefix.replace(START, "").rstrip() + "\n# ... EVOLVE-BLOCK ...\n"
                 + self.seed_prog.suffix.replace(END, "").strip() + "\n```\n",
                 f"# Current program (id {parent.id}, train score {parent.score:.3f} {self.spec.unit})\n"
                 f"<current_block>\n{parent.block}</current_block>\n\nEvaluator insights for the current program:\n"
                 f"{fmt_ins(parent)}\n"]
        for k, c in enumerate(insp, 1):
            parts.append(f"# Inspiration {k} (id {c.id}, island {c.island}, score {c.score:.3f})\n```python\n{c.block}```\n"
                         f"Insights:\n{fmt_ins(c, 5)}\n")
        bad = self._recent_invalid()
        if bad:
            parts.append("# Recent INVALID candidates (do not repeat these mistakes)\n" + "\n".join(f"- {b}" for b in bad) + "\n")
        parts.append("# Task\nPropose ONE focused, economically motivated improvement to the current program that raises "
                     "the score while keeping every invariant satisfied. Prefer changes a pricing or trading desk could "
                     "explain to a regulator. Reply with the rationale and SEARCH/REPLACE blocks only.")
        return "\n".join(parts)

    def _pick_model(self) -> str:
        mix = model_policy.mutator_mix()
        return self.rng.choices([m["name"] for m in mix], weights=[m["weight"] for m in mix])[0]

    # -- one generation + evaluation ---------------------------------------------------------------
    def _work(self, idx: int, island: int, parent: Candidate, insp: list[Candidate], model: str) -> Candidate:
        prompt = self.build_prompt(parent, insp)
        g = self.mutator.generate(model, SYSTEM_PROMPT, prompt)
        gen = {"model": g.model, "prompt_tokens": g.prompt_tokens, "output_tokens": g.output_tokens,
               "thinking_tokens": g.thinking_tokens, "latency_s": g.latency_s, "cost_usd": g.cost_usd,
               "error": g.error, "attempts": g.attempts}
        with self.lock:
            t = self.tokens
            t["calls"] += 1
            t["prompt"] += g.prompt_tokens
            t["output"] += g.output_tokens
            t["thinking"] += g.thinking_tokens
            t["cost_usd"] = round(t["cost_usd"] + g.cost_usd, 6)
            t["errors"] += 1 if g.error else 0
            bm = t["by_model"].setdefault(g.model, {"calls": 0, "prompt": 0, "output": 0, "thinking": 0, "cost_usd": 0.0})
            bm["calls"] += 1
            bm["prompt"] += g.prompt_tokens
            bm["output"] += g.output_tokens
            bm["thinking"] += g.thinking_tokens
            bm["cost_usd"] = round(bm["cost_usd"] + g.cost_usd, 6)
        rationale = g.text.split("<<<<<<<")[0].strip()[:1500] if g.text else ""
        reply = (g.text or "")[:12000]
        if g.error:
            out = EvalOutcome(score=None, kind="generation", insights=[("generation", f"model call failed: {g.error}")])
            return Candidate(idx, _pid(parent.block, idx), parent.id, island, parent.block, g.model, out, rationale, gen,
                             inspirations=[c.id for c in insp])
        try:
            block, rep = apply_reply(parent.block, g.text, self.spec.required_functions)
            drep = {"hunks": rep.hunks, "applied": rep.applied, "methods": rep.methods, "failures": rep.failures,
                    "mode": rep.mode}
        except DiffError as e:
            out = EvalOutcome(score=None, kind=KIND_DIFF, insights=[("diff", f"could not apply the reply: {e}")])
            return Candidate(idx, _pid(parent.block + str(idx), idx), parent.id, island, parent.block, g.model, out,
                             rationale, gen, {"error": str(e)}, inspirations=[c.id for c in insp], reply=reply)
        src = assemble(self.seed_prog.prefix, block, self.seed_prog.suffix)
        out = evaluate_candidate(self.spec, src, "train")
        c = Candidate(idx, _pid(block, idx), parent.id, island, block, g.model, out, rationale, gen, drep,
                      inspirations=[c.id for c in insp], reply=reply if not out.valid else "")
        if out.valid:
            try:
                c.descriptor = tuple(self.spec.descriptor(out))
            except Exception:  # noqa: BLE001
                c.descriptor = (0, 0)
        return c

    def _admit(self, c: Candidate) -> None:
        self.cands.append(c)
        self.island_members[c.island].append(c.idx)
        if c.score is not None and c.descriptor is not None:
            key = (c.island, c.descriptor)
            cur = self.archive.get(key)
            if cur is None or self.cands[cur].score < c.score:
                self.archive[key] = c.idx

    def _migrate(self) -> None:
        for i in range(self.n_islands):
            valid = self._valid(self.island_members[i])
            if not valid:
                continue
            b = max(valid, key=lambda j: self.cands[j].score)
            tgt = (i + 1) % self.n_islands
            if b not in self.island_members[tgt]:
                self.island_members[tgt].append(b)

    # -- run ---------------------------------------------------------------------------------------
    def run(self) -> dict:
        spec = self.spec
        started = datetime.now(timezone.utc)
        t0 = time.monotonic()
        lock_report = verify_baseline(spec)                       # refuses to start on an unlocked baseline
        budget_state = self.ledger.check_can_start(spec.name, self.max_programs, self.policy)
        writer = EvidenceWriter(spec.name, started, self.runs_dir)
        self.ledger.reserve({"run_id": writer.run_id, "problem": spec.name, "started": started.isoformat(),
                             "source": self.source, "programs": self.max_programs,
                             "counts_against_budget": not self.dry_run})
        self.log(f"[{writer.run_id}] baseline locked: seed={lock_report['seed_score']:.3f} null_raw="
                 f"{lock_report['null_raw']} ; budget {budget_state}")
        seed_out = evaluate_candidate(spec, spec.seed_src, "train")
        seed = Candidate(0, _pid(self.seed_prog.block, 0), None, 0, self.seed_prog.block, "seed", seed_out,
                         "seed program (hand-written baseline)")
        seed.descriptor = tuple(spec.descriptor(seed_out)) if seed_out.valid else (0, 0)
        self.cands.append(seed)
        for i in range(self.n_islands):
            self.island_members[i].append(0)
            self.archive[(i, seed.descriptor)] = 0
        plateau = PlateauTracker(self.policy.plateau_patience, seed.score)
        submitted = 0
        next_island = 0
        in_flight: dict[Future, int] = {}
        record_base = self._record_base(writer.run_id, started, lock_report)
        with ThreadPoolExecutor(max_workers=self.policy.concurrency) as pool:
            while True:
                elapsed = time.monotonic() - t0
                stop = None
                if submitted >= self.max_programs:
                    stop = "max_programs"
                elif elapsed >= self.policy.max_wall_s:
                    stop = "wall_clock"
                elif plateau.plateaued:
                    stop = "plateau"
                if stop is None and len(in_flight) < self.policy.concurrency:
                    submitted += 1
                    island = next_island
                    next_island = (next_island + 1) % self.n_islands
                    with self.lock:
                        parent = self._select_parent(island)
                        insp = self._inspirations(island, parent)
                    model = self._pick_model()
                    f = pool.submit(self._work, submitted, island, parent, insp, model)
                    in_flight[f] = submitted
                    continue
                if not in_flight:
                    self.stopped_reason = stop or self.stopped_reason
                    break
                done, _ = wait(list(in_flight), timeout=5, return_when=FIRST_COMPLETED)
                for f in done:
                    in_flight.pop(f)
                    try:
                        c = f.result()
                    except Exception as e:  # noqa: BLE001
                        c = Candidate(len(self.cands), f"p{len(self.cands):03d}-error", None, 0, self.seed_prog.block,
                                      "error", EvalOutcome(None, "controller_error", [("controller_error", repr(e)[:400])]))
                    with self.lock:
                        c.idx = len(self.cands)
                        self._admit(c)
                        plateau.update(c.score)
                        if len(self.cands) % 10 == 0:
                            self._migrate()
                    b = self.best()
                    self.log(f"[{writer.run_id}] #{c.idx:02d} island {c.island} {c.model:24s} "
                             f"{'VALID ' if c.score is not None else 'INVALID'} score={c.score if c.score is None else round(c.score, 3)} "
                             f"kind={c.outcome.kind if c.outcome else '-'} best={b.score:.3f} plateau={plateau.since}/{self.policy.plateau_patience}"
                             + ("" if c.score is not None else f" :: {(c.outcome.insights[0][1] if c.outcome and c.outcome.insights else '')[:140]}"))
                    writer.progress(self._record(record_base, time.monotonic() - t0, plateau, final=False))
                if stop is not None:
                    self.stopped_reason = stop
        wall = time.monotonic() - t0
        self.log(f"[{writer.run_id}] search stopped ({self.stopped_reason}) after {len(self.cands) - 1} programs, {wall:.0f} s; holdout rescoring...")
        holdout = self._holdout()
        record = self._record(record_base, wall, plateau, final=True, holdout=holdout)
        path = writer.finalize(record)
        self.ledger.record(writer.run_id, status="finished", finished=datetime.now(timezone.utc).isoformat(),
                           programs=len(self.cands) - 1, wall_s=round(wall, 1), stopped_reason=self.stopped_reason,
                           cost_usd=self.tokens["cost_usd"], tokens=self.tokens["prompt"] + self.tokens["output"] + self.tokens["thinking"],
                           holdout_delta=holdout.get("holdout_delta"), uplift_valid=record["uplift_valid"])
        self.log(f"[{writer.run_id}] evidence -> {path}")
        return record

    # -- holdout -----------------------------------------------------------------------------------
    def _holdout(self) -> dict:
        spec = self.spec
        hf = spec.holdout_fold
        seed_h = evaluate_candidate(spec, spec.seed_src, hf)
        null_h = evaluate_candidate(spec, spec.null_src, hf)
        valid = sorted([c for c in self.cands if c.score is not None], key=lambda c: c.score, reverse=True)
        top, seen = [], set()
        for c in valid:
            if c.block_sha in seen:
                continue
            seen.add(c.block_sha)
            top.append(c)
            if len(top) >= self.top_k:
                break
        rows = []
        for c in top:
            src = assemble(self.seed_prog.prefix, c.block, self.seed_prog.suffix)
            o = seed_h if c.idx == 0 else evaluate_candidate(spec, src, hf)
            rows.append({"id": c.id, "idx": c.idx, "train": c.score, "holdout": o.score, "holdout_valid": o.valid,
                         "holdout_kind": o.kind, "holdout_metrics": o.metrics,
                         "holdout_insights": [{"label": l, "text": t} for l, t in o.insights[:8]]})
        champion = rows[0] if rows else None      # selected on TRAIN score only; holdout is reported, not searched
        best_holdout = champion["holdout"] if champion else None
        delta = (best_holdout - seed_h.score) if (best_holdout is not None and seed_h.score is not None) else None
        max_row = max((r for r in rows if r["holdout"] is not None), key=lambda r: r["holdout"], default=None)
        return {"fold": hf, "seed": seed_h.score, "seed_valid": seed_h.valid, "seed_metrics": seed_h.metrics,
                "seed_insights": [{"label": l, "text": t} for l, t in seed_h.insights[:8]],
                "null": null_h.score, "null_raw": null_h.raw_score, "null_valid": null_h.valid,
                "null_insights": [{"label": l, "text": t} for l, t in null_h.insights[:6]],
                "top_k": rows, "best_id": champion["id"] if champion else None,
                "best_is_seed": bool(champion and champion["idx"] == 0),
                "best_holdout": best_holdout, "holdout_delta": delta,
                "selection": "champion = best TRAIN score among valid candidates; holdout is only reported",
                "max_holdout_in_top_k": max_row["holdout"] if max_row else None,
                "max_holdout_id": max_row["id"] if max_row else None}

    # -- evidence ----------------------------------------------------------------------------------
    def _record_base(self, run_id: str, started: datetime, lock_report: dict) -> dict:
        man = load_manifest()["instances"]
        return {"schema": SCHEMA, "run_id": run_id, "problem": self.spec.name, "title": self.spec.title,
                "evaluator_version": self.spec.version,
                "source": self.source, "backend": "local", "evolved": False,
                "honesty_note": ("AlphaEvolve-compatible run, local controller; production run pending GE app "
                                 "provisioning; switching is one flag (--backend alphaevolve)."),
                "started": started.isoformat(), "mutator": getattr(self.mutator, "kind", "?"),
                "model_mix": model_policy.mutator_mix(), "pricing_note": model_policy.PRICING_NOTE,
                "instances": {f: {"name": f"{self.spec.name}_{n}", "sha256": man[f"{self.spec.name}_{n}"]["sha256"]}
                              for f, n in (("train", "train"), ("holdout", self.spec.holdout_fold))},
                "holdout_fold": self.spec.holdout_fold,
                "baseline_lock": lock_report, "budget_policy": policy_dict(self.policy),
                "search": {"islands": self.n_islands, "archive": "MAP-Elites-lite", "descriptor": list(self.spec.descriptor_names),
                           "parent_selection": "rank-weighted 0.6 / random elite 0.4", "migration_every": 10,
                           "diff_format": "SEARCH/REPLACE inside EVOLVE-BLOCK"},
                "unit": self.spec.unit}

    def _prog_row(self, c: Candidate) -> dict:
        parent = next((p for p in self.cands if p.id == c.parent_id), None)
        o = c.outcome.to_record() if c.outcome else {}
        return {"idx": c.idx, "id": c.id, "parent_id": c.parent_id, "island": c.island, "model": c.model,
                "created": c.created, "score": o.get("score"), "raw_score": o.get("raw_score"), "valid": o.get("valid", False),
                "kind": o.get("kind"), "insights": o.get("insights", []), "metrics": o.get("metrics", {}),
                "violations": (c.outcome.details.get("violations") if c.outcome else None),
                "eval_s": (c.outcome.details.get("eval_s") if c.outcome else None),
                "descriptor": list(c.descriptor) if c.descriptor else None, "block_sha": c.block_sha, "block": c.block,
                "diff_vs_parent": unified(parent.block, c.block, "parent", "child") if parent else "",
                "diff_stats": diff_stats(parent.block, c.block) if parent else {}, "rationale": c.rationale,
                "generation": c.gen, "diff_report": c.diff_report, "inspirations": c.inspirations,
                "raw_reply_if_unparsed_or_invalid": c.reply}

    def _record(self, base: dict, wall: float, plateau: PlateauTracker, final: bool, holdout: dict | None = None) -> dict:
        seed = self.cands[0]
        b = self.best()
        curve, best_so_far = [], None
        for c in self.cands:
            if c.score is not None and (best_so_far is None or c.score > best_so_far):
                best_so_far = c.score
            curve.append({"idx": c.idx, "score": c.score, "best": best_so_far, "valid": c.score is not None,
                          "kind": c.outcome.kind if c.outcome else None, "island": c.island})
        catches: dict[str, int] = {}
        for c in self.cands[1:]:
            if c.outcome and not c.outcome.valid:
                key = c.outcome.kind
                if key == "policy":
                    for v in c.outcome.details.get("violations", []) or [{"invariant": "policy"}]:
                        catches[f"policy:{v.get('invariant')}"] = catches.get(f"policy:{v.get('invariant')}", 0) + 1
                else:
                    catches[key] = catches.get(key, 0) + 1
        rec = {**base, "finished": datetime.now(timezone.utc).isoformat() if final else None,
               "budget": {"programs_evaluated": len(self.cands) - 1, "max_programs": self.max_programs,
                          "wall_s": round(wall, 1), "stopped_reason": self.stopped_reason,
                          "plateau_since": plateau.since, "concurrency": self.policy.concurrency},
               "tokens": self.tokens, "score_curve": curve, "invalid_by_kind": catches,
               "valid_count": sum(1 for c in self.cands[1:] if c.score is not None),
               "invalid_count": sum(1 for c in self.cands[1:] if c.score is None),
               "seed": {"id": seed.id, "train": seed.score, "metrics": seed.outcome.metrics if seed.outcome else {}},
               "best": None, "programs": [self._prog_row(c) for c in self.cands],
               "islands": {str(i): {"members": len(m), "best": max((self.cands[j].score for j in self._valid(m)), default=None)}
                           for i, m in self.island_members.items()}}
        if b:
            rec["best"] = {"id": b.id, "idx": b.idx, "train": b.score, "metrics": b.outcome.metrics, "island": b.island,
                           "model": b.model, "block": b.block, "train_delta_vs_seed": (b.score - seed.score) if seed.score is not None else None,
                           "diff_vs_seed": unified(seed.block, b.block, "seed", b.id), "lineage": self._lineage(b)}
        if holdout is not None:
            rec["holdout"] = holdout
            d = holdout.get("holdout_delta")
            champ = next((r for r in holdout["top_k"] if r["id"] == holdout.get("best_id")), None)
            if champ is None or holdout.get("best_is_seed"):
                rec["uplift_valid"] = False
                rec["uplift_note"] = "no candidate beat the seed on train; nothing to promote"
            elif not champ["holdout_valid"]:
                rec["uplift_valid"] = False
                rec["uplift_note"] = "champion violates a policy invariant on holdout: " + "; ".join(
                    i["text"][:200] for i in champ["holdout_insights"][:2])
            elif d is None or d <= 0:
                rec["uplift_valid"] = False
                rec["uplift_note"] = f"no holdout uplift (holdout_delta={d})"
            else:
                rec["uplift_valid"] = True
                rec["uplift_note"] = (f"holdout_delta={d:.3f} {self.spec.unit} under all policy invariants; "
                                      "evidence is from the local controller, so evolved stays false")
            rec["evolved"] = False
        return rec

    def _lineage(self, c: Candidate) -> list[dict]:
        out, cur = [], c
        by_id = {x.id: x for x in self.cands}
        while cur is not None:
            out.append({"id": cur.id, "score": cur.score, "model": cur.model, "rationale": cur.rationale[:600]})
            cur = by_id.get(cur.parent_id) if cur.parent_id else None
        return list(reversed(out))


def run_local(spec: ProblemSpec, *, dry_run: bool = False, **kw: Any) -> dict:
    from .llm import DryRunMutator, GeminiMutator

    mutator = DryRunMutator() if dry_run else GeminiMutator()
    return LocalController(spec, mutator, dry_run=dry_run, **kw).run()
